server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  profiles:
    active: real   # ?? ???? ??? ?? ??
  jpa:
    hibernate:
      ddl-auto: create
      profiles:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        default_batch_fetch_size: 100
  data:
    web:
      pageable:
        default-page-size: 20
        one-indexed-parameters: true